services:
  - type: web
    name: zeyfira-dreamscape
    env: node
    buildCommand: chmod +x ./build.sh && ./build.sh
    startCommand: chmod +x ./start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable 